version: '3.4'

services:
  master:
    container_name: master
    image: redis:6.0.9
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=master:master
    ports:
    - "8081:8081"

